### PR TITLE
Implementation of Theme for Dark Mode

### PR DESCRIPTION
**Pull request by RITIK-CHAUDHRY**
## Description

fixed issue #1

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Related Issue

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Screenshots (if appropriate):

Uploading Screen_Recording_20241024_165140_Jedi Share.mp4…

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [ ] My code follows the code style of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by RITIK-CHAUDHRY** [comment]
https://github.com/user-attachments/assets/ed636956-7614-4215-b619-f3614f184b75

**Comment by SaiDheerajPeketi** [comment]
@RITIK-CHAUDHRY It seems like you've added colors for dark theme but everything looks the same as the default dark theme,
There are a few issues:
1) Settings screen is still white (out of theme).
2) In the select files screen there's a balancing Home that is not themed.
3) The splash screen is also not themed.

**Comment by RITIK-CHAUDHRY** [comment]
@SaiDheerajPeketi i will fix these mam by 2am

**Comment by SaiDheerajPeketi** [comment]
> @SaiDheerajPeketi i will fix these mam by 2am

*sir

**Comment by RITIK-CHAUDHRY** [comment]
@SaiDheerajPeketi sir today is last day of contrihub and hacktoberfest. I request you please merge the PR and give the adequate points according to you in contrihub and so the hacktoberfest.

Apologies for not completing 100% of the work. I had tried my best but my persistent health issues restricts my performance.

Wish you a happy diwali sir..

**Pull request merged**
